woocommerce/woocommerce-accommodation-bookings

includes/admin/class-wc-accommodation-booking-admin-meta-box.php, includes/class-wc-accommodation-booking.php, includes/class-wc-product-accommodation-booking.php, woocommerce-accommodation-bookings.php
This PR makes the "booking details" screen slightly more useful for accommodation bookings.
* The booking type is mentioned at the top of the screen letting you know it is an accommodation.
* Accommodation products are now loaded into the "booked products" drop down.
* Start/end time correctly displays check-in/check-out time from global settings.
* All-day check box has been hidden.
Related: https://github.com/woothemes/woocommerce-bookings/pull/590
Please review @gedex
=> Accommodation Bookings 1.0.2: Booking Details Screen

includes/admin/views/html-accommodation-booking-rates-fields.php, includes/admin/views/html-accommodation-booking-rates.php
These actions allow extending the functionality around pricing.
Since the accommodation products use a different UI than the standard WooCommerce products it’s not currently possible to customize this to add separate fields for alternative costs.
Actions that allow one to add custom fields for costs:
do_action( 'woocommerce_accommodation_bookings_after_booking_base_cost', $post_id );
allows adding a custom price field (e.g. in a different currency) for Standard room rate cost
do_action( 'woocommerce_accommodation_bookings_after_booking_pricing_override_block_cost', $rate, $post_id );
allows adding a custom price field (e.g. in a different currency) for Range cost
An action that allows hooking into the costs UI below all the costs fields
do_action( …
=> Add actions for extending the pricing

includes/class-wc-accommodation-booking-order-info.php
Bookings saved localised strings for 'Booking Data' and 'Duration' as
order item meta. This means user with non-english site may store
different meta key.
Resolves #25.
=> Fixed fatal error when 'Booking Data' or 'Duration' does not exists.

includes/admin/views/html-accommodation-booking-data.php, includes/class-wc-accommodation-booking-order-info.php
Fixes #50.
Use text domain `woocommerce-accommodation-bookings` to avoid confusion in POT file for translators.
=> Fixed wrong text domain being used.

includes/admin/class-wc-accommodation-booking-admin-panels.php
Fixes # .
No bug open for this.
`writepanel.js` is being included on all admin pages, which causes a JS error on all pages that are not product pages.
- Wrapped the enqueue function with if statement checking to make sure the post type is `product`.
=> Set writepanel.js to only be included on product admin pages

includes/admin/class-wc-accommodation-booking-admin-panels.php, includes/admin/views/html-accommodation-booking-rates.php
- Added Display Cost tab to account for offset mentioned in #60 
=> Added Display Cost field and test for screen id for loading js/css

includes/class-wc-accommodation-booking.php, readme.txt, woocommerce-accommodation-bookings.php
Updated time uses check in/out time. The value doesn't update the time
when existing booking is updated. Otherwiwe it always overrides what
ever user supplies.
Fixes #69.
=> When new booking is created, update its start and end time.

includes/class-wc-accommodation-dependencies.php
Also, making sure to check the correct plugin's main filename when
1.9.11 is released.
Resolves #63.
=> Check class existence in case plugin's path is not the expectend one.

includes/admin/class-wc-accommodation-booking-admin-panels.php, includes/class-wc-accommodation-bookings-plugin.php, includes/class-wc-product-accommodation-booking.php
The change at https://github.com/woocommerce/woocommerce-bookings/commit/2d4c7ae8#diff-fc37c2ec242b590decd6ee7fbf8d5c4cL52 broke `woocommerce-accomodation-bookings` and `woocommerce-bookings`. I get `( ! ) Fatal error: Class 'WC_Product_Booking' not found in /Users/boro/dev/woocommerce-accommodation-bookings/includes/class-wc-product-accommodation-booking.php on line 10` (edited)
This is because `woocommerce-accomodation-bookings` triggers on `woocommerce_loaded` with priority 20, but it seems this triggers before `plugins_loaded`.
As for whether this will work with Bookings pre 1.10, in theory, I think it should be good.
Bookings pre 1.10 will use `woocommerce_loaded` which triggers before `plugins_loaded`
=> Fix some notices and error on plugin activation.

includes/class-wc-product-accommodation-booking.php
Fixes #97.
- We need to override `get_type` to the proper type, as when eventually lands [here](https://github.com/woocommerce/woocommerce/blob/master/includes/abstracts/abstract-wc-product.php#L124) it calculates properly.
=> Allow accommodation product to be created.

includes/class-wc-product-accommodation-booking.php
Fixes #105.
- Wrap the class definition in a `class_exists` check
=> Fix fatal error in case the plugin is included multiple times.

includes/class-wc-accommodation-booking-date-picker.php, includes/class-wc-accommodation-bookings-plugin.php, includes/class-wc-product-accommodation-booking-resource.php, includes/class-wc-product-accommodation-booking.php, package.json, readme.txt, woocommerce-accommodation-bookings.php
Alters #108 (add support for resources). Fixes #87, #107, #110.
- Need to override a bunch of Bookings methods which depend on type. They were checking `bookings` against `WC_Product_Accommodation_Booking::get_type` which is `accommodation-bookings`.
- Alter availability logic to handle products with resources
- Remove old code which was skipping until check date matches current timestamp (today) to fix #110.
=> Fix resource calculation issue.

includes/class-wc-product-accommodation-booking.php
Fixes #114 .
- Removed code that was incorrectly dividing the price between min available days. 
=> removed code that was displaying incorrect price

includes/admin/views/html-accommodation-booking-data.php
-Tax fields were not being shown due to incorrect css class was being used. 
=> Fixed css class to show tax fields

includes/class-wc-accommodation-booking-date-picker.php, readme.txt
Fixes #112 .
- When `today` is start of the booking it should be marked as fully booked as there are no more actions available for that day. 
=> Fix 112 Today showing partially available when not available.

includes/class-wc-product-accommodation-booking.php, readme.txt
Fixes #126 .
- Added `woocommerce_accommodation_bookings_range_picker_enabled` filter to be able to disable the range picker, if desired. 
- Bookings master already has a fix in for *Nights(s)*
=> Added filter to allow range picker to be disabled

includes/admin/class-wc-accommodation-booking-admin-panels.php, includes/admin/views/html-accommodation-booking-availability.php
Fixes backward compatibility so that this will work with Bookings versions less than 1.10.7 .
- Use `version_compare` to skip the blocks of code that implement restricted days.
=> Added version_compare for Bookings < 1.10.7 compat

includes/class-wc-accommodation-booking-date-picker.php, readme.txt
Fixes #142 .
- Use `get_all_existing_bookings` instead of `get_bookings_for_objects` so that min/max dates are added to query. 
=> Bookings outside of available range being checked for availability

includes/admin/views/html-accommodation-booking-data.php, readme.txt
Fixes #148
- Set the `min` value of the field to `1`.
=> Set the minimum value for max nights to 1

includes/admin/class-wc-accommodation-booking-admin-panels.php, readme.txt
Fixes #124 .
- Update `_wc_booking_block_cost` with base cost on save
- Remove `_wc_booking_cost` on save, accomodations doesn't use it and it causes issues when toggling a product between Booking and Accomodation.
=> Reset booking cost on save and update block cost with the base cost

includes/class-wc-accommodation-booking.php
Fixes #160.
- This pull request will test if `product-booking` exists in the array passed to `register_data_stores` before using it
=> Fix undefined index for product-booking #160

package.json
- Adds 'grunt' to the npm start command.  Since I do not have grunt installed globally I need to run it from the node_modules folder.
=> Adds npm start script so Grunt does not have to be installed globally

includes/class-wc-accommodation-bookings-plugin.php, readme.txt
Fixes #197
* Fix - Check product object before calling method to prevent errors.
=> Check product object exists before calling its methods closes #197

changelog.txt, includes/class-wc-product-accommodation-booking.php
Accommodation differs from the standard booking product as the duration is always one night.
Overwriting this duration fetching function acts as a compatibility layer. It is possible to create a and set parameters for a booking product. Later it is possible to change the product type to accommodation. Some of the fields are hidden but still remain set. This prevents now
hidden duration field from having an effect on the calculation.
Fixes #185 .
=> Accommodation duration unit is always one night.

changelog.txt, includes/class-wc-product-accommodation-booking.php
Fixes #215 
* Fix - Mismatch function declaration causing PHP warnings.
=> Match function declarations closes #215

package.json
Fixes https://github.com/woocommerce/woocommerce-extension-release/issues/22
=> Add wp_org_slug for .org release support in woocommerce-extension-release

changelog.txt, includes/class-wc-accommodation-booking.php
Fixes #209
#209 occurs because accommodation-bookings provides a simplified UX for modifying accommodations rates, which is hiding how Bookings is actually applying rate adjustments.
For Accommodation products, if a special rate is required, you directly enter that rate like this:
Which results in $1000/night for every night, except on December 23rd/24th, the accommodation rate is $100/night.
Behind the scenes, though, this rate is saved like this for the core Booking code: 
So, the block cost is $1000, but we're subtracting $900 on those dates. The result is still $100/night.
Unfortunately, you end up with some really confusing behavior (hence #209) if you have multiple rates applying to the same day, because core Bookings is actually adding all of these rate adjustments together. So, if …
=> Fix Overlapping Rates

changelog.txt, includes/class-wc-accommodation-booking.php
Fixes #221  when used with https://github.com/woocommerce/woocommerce-bookings/tree/fix/issue-221
Uses new filter in Bookings 'woocommerce_bookings_resource_duration_display_string' to display 'night' resource duration.
How to test:
1. Activate Bookings with the new filter (Branch fix/issue-221) and Accommodation bookings.
2. Build the plugin and translate 'night' into Spanish (Ex: Using Loco Translate)
3. Create an accommodation product (with a standard room rate).
4. Add customer selected resources to the product with a block cost.
5. View the product
6. Change the site language to Spanish, view the product and check the resource duration is translated.
=> Fix missing translation for resource duration display.

changelog.txt, composer.json, phpunit.xml, tests/phpunit/bootstrap.php, tests/phpunit/test-class-wc-accommodation-booking.php
Fixes #244  .
Basic skeleton to add unit/integration tests.
=> Add Basic Unit tests suite.

changelog.txt, includes/class-wc-accommodation-booking-date-picker.php
When looping through existing bookings to display on the datepicker, loop through the checkin dates and not just the checkout dates. This will then mark both the checkin and checkout dates as "partially booked" which will allow users to select an existing booking's checkout date as their booking's checkout date.
This commit was responsible for the issue:
https://github.com/woocommerce/woocommerce-accommodation-bookings/pull/237/commits/0d42f97a9a474ad9865132bb10245576cef17d92
It was to fix #235 which I've re-tested and is not a problem with this PR branch, so, fixing this "regression" doesn't appear to cause a different regression. :P
It would be good to re-test the conditions in #235 as well.
Closes #250 
See this GIF for the new behavior:
Existing behavior(in master):
1. View an …
=> Allow existing booking checkout date to be selectable.

package.json
Splits out the build into two separate steps:
1. Build for release
- Includes only non dev dependencies in composer
- Creates a zip archive
2. Build for development
- Includes all dependencies in composer (including dev)
- Generates all resources, but does not create a zip archive
Note: For extensions that don't have any composer dependencies we don't run composer install at all so the autoloader isn't included.
Closes https://github.com/woocommerce/woocommerce-extension-library/issues/130
1. Run `npm install && npm run build`
2. Confirm that the zip archive is created and doesn't contain any dev dependencies (most our extensions won't have any)
=> Add dev build script
