woocommerce/woocommerce-accommodation-bookings

includes/admin/views/html-accommodation-booking-availability-fields.php
includes/admin/views/html-accommodation-booking-rates-fields.php

Fixes 'Febuary' typo to 'February'.

---

readme.txt

Missing preposition in sentence

---

woocommerce-accommodation-bookings.php

Update docs link

---

includes/class-wc-accommodation-booking-cart-manager.php
includes/class-wc-accommodation-booking-order-info.php
readme.txt
woocommerce-accommodation-bookings.php

Fixes #11 and matches how the start date is passed.
cc @gedex

Calculate accurate end times when using other date formats

---

includes/class-wc-accommodation-booking-order-info.php

Fixes incorrect end date timestamp calculation in order info.

---

includes/class-wc-accommodation-booking.php

This will make accommodation-booking included in the dropdown of
products.
Resolves #23 and #15.

Hooked into `get_booking_products_args`.

---

includes/class-wc-accommodation-bookings-plugin.php
includes/class-wc-accommodation-dependencies.php
woocommerce-accommodation-bookings.php

Resolves #20. Also resolves #21.

Better dependencies checker by notifying user if not satisfied.

---

includes/class-wc-accommodation-booking-order-info.php

fixes #36
@roykho Please review

Avoid accessing the date time object if false was give by datecreate

---

includes/admin/class-wc-accommodation-booking-admin-panels.php
includes/class-wc-accommodation-booking-product-tabs.php
includes/class-wc-accommodation-bookings-plugin.php
includes/integrations/class-wc-accommodation-booking-addons.php

Fixes #78 #75 
- Fix deprecated API's
- Fix translation issue.
---
@gedex please review.

minor changes

---

includes/class-wc-accommodation-booking-date-picker.php

Move code out for $posted data out of bookings core and into this extension by using the new filter introduced in bookings 1.9.13
@roykho please review. Related to changes here: https://github.com/woocommerce/woocommerce-bookings/pull/849/files

moved adding code from core boookings to extension

---

includes/class-wc-accommodation-booking-cart-manager.php
includes/class-wc-accommodation-booking-date-picker.php
includes/class-wc-accommodation-booking-order-info.php
includes/class-wc-accommodation-booking-product-tabs.php
includes/class-wc-accommodation-booking.php
includes/class-wc-accommodation-bookings-plugin.php
includes/class-wc-product-accommodation-booking.php
includes/integrations/class-wc-accommodation-booking-addons.php
package.json
readme.txt
woocommerce-accommodation-bookings.php

- Updates for WC 3.0 compatibility.

Updates for WC 3.0 compatibility.

---

includes/class-wc-accommodation-booking-date-picker.php

Fixes #76.
- Implemented logic where:
* Bookings will be marked as partially booked for their start and end dates.
* Everything in between will be marked as fully booked.
* If booking A checks in on X and booking B checks out on X, mark X as fully booked.

Fix the logic for booked checkin and checkout days

---

includes/class-wc-accommodation-booking-date-picker.php
package.json
readme.txt
woocommerce-accommodation-bookings.php

Fixes #120.
- Use availability rules by adding logic for it

Use availability rules by adding logic for it

---

includes/admin/class-wc-accommodation-booking-admin-product-settings.php
includes/class-wc-accommodation-booking-cart-manager.php
includes/class-wc-accommodation-booking-date-picker.php
includes/class-wc-accommodation-booking-order-info.php
includes/class-wc-accommodation-booking-product-tabs.php
includes/class-wc-accommodation-booking.php
includes/class-wc-product-accommodation-booking.php
readme.txt

Fixes #133.
- Fix issue by setting default values for checkin/checkout

Fix issue by setting default values for checkin/checkout

---

includes/class-wc-accommodation-booking-date-picker.php
readme.txt

Fixes #138.
- Fix issue by adding an isset check

Fix issue by adding an isset check

---

includes/admin/class-wc-accommodation-booking-admin-product-settings.php
readme.txt

Fixes #153.
- Fix corrupted dates

Fix corrupted dates

---

includes/class-wc-product-accommodation-booking-resource.php
includes/class-wc-product-accommodation-booking.php
readme.txt

Fixes #164.
- Fix issue by checking whether Bookings class exists

Fix issue by checking whether Bookings class exists

---

includes/class-wc-accommodation-booking-order-info.php
readme.txt

Fixes https://github.com/woocommerce/woocommerce-account-funds/issues/120.
- Check product before using it

Check product before using it

---

readme.txt

Fixes #124  .
- Adding FAQ for cached prices

Adding FAQ for cached prices

---

includes/admin/class-wc-accommodation-booking-admin-panels.php
includes/class-wc-accommodation-booking-order-manager.php
includes/class-wc-accommodation-bookings-plugin.php
readme.txt

Fixes #179.
- Allow virtual accommodation products

Allow virtual accommodation products

---

includes/admin/class-wc-accommodation-booking-admin-panels.php
includes/admin/views/html-accommodation-booking-rates-fields.php
includes/class-wc-accommodation-bookings-plugin.php
readme.txt

Fixes #141.
- See explanation at https://github.com/woocommerce/woocommerce-accommodation-bookings/issues/141#issuecomment-370357027

Fix issue by changing how rules are saved

---

includes/class-wc-accommodation-booking-cart-manager.php
includes/integrations/class-wc-accommodation-booking-addons.php
readme.txt

Added compatibility code for Product Add-ons 3.0.

Add PAO 3.0 compat

---

package-lock.json
package.json

Fixes #245 .
- Update package.json and package-lock.json to fix vulnerable security warnings from npm.

Update npm dependencies to fix vulnerabilities.

---

changelog.txt
includes/admin/class-wc-accommodation-booking-admin-panels.php
includes/admin/views/html-accommodation-booking-rates-fields.php

Closes #238 .
Follow directions in #238
Fix - Do not round input values for range types.

Do not round input values for range types.
